version: "3"
services:
  server:
    container_name: DLT_Chatbot
    build: .
    ports:
      - "51000:5000"
    restart: always
    volumes:
      - ./:/usr/src/app/
    command: >
      sh -c "npm start"
